name: Build ROS2 Core Docker Images

on:
  push:
    branches: [ "main", "develop" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        variant: [cpu, nvidia]
        include:
          - variant: cpu
            dockerfile: .devcontainer/linux-cpu/Dockerfile
            base_image: althack/ros2:jazzy-gazebo
            tags_suffix: cpu
          - variant: nvidia
            dockerfile: .devcontainer/linux-nvidia/Dockerfile
            base_image: althack/ros2:jazzy-cuda-gazebo
            tags_suffix: nvidia

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.tags_suffix }}
            type=ref,event=pr,suffix=-${{ matrix.tags_suffix }}
            type=semver,pattern={{version}},suffix=-${{ matrix.tags_suffix }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.tags_suffix }}
            type=raw,value=latest,suffix=-${{ matrix.tags_suffix }},enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            WORKSPACE=/workspaces/ros2_ws

  build-summary:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Build Summary
        run: |
          echo "## Build Results" >> $GITHUB_STEP_SUMMARY
          echo "| Variant | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| CPU | ${{ needs.build-and-push.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| NVIDIA | ${{ needs.build-and-push.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Image Tags:" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-cpu\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-nvidia\`" >> $GITHUB_STEP_SUMMARY
